# Generated by Django 3.2.4 on 2021-06-15 14:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noughtpad_app', '0003_auto_20210613_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='preview',
            field=models.TextField(default='Lorem ipsum', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
