# Generated by Django 3.2.4 on 2021-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noughtpad_app', '0005_remove_note_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
